### ISSUE TITLE
AuthenticationException shouldn't be thrown when user denies access

### ISSUE THREAD

**Issue by ThomasArdal** [SimpleAuthentication/SimpleAuthentication#170]
I get the following exception in my log:

SimpleAuthentication.Core.Exceptions.AuthenticationException: Reason: user_denied. Error: access_denied. Description: Permissions error.
   at SimpleAuthentication.Core.Providers.FacebookProvider.RetrieveAuthorizationCode(NameValueCollection queryStringParameters)
   at SimpleAuthentication.Core.Providers.BaseOAuth20Provider`1.AuthenticateClient(NameValueCollection queryStringParameters, String state, Uri callbackUri)
   at SimpleAuthentication.Mvc.SimpleAuthenticationController.AuthenticateCallback(AuthenticateCallBackInputModel inputModel)

From what I can find in the documentation, the user_denied/access_denied is caused by the fact that the user doesn't accept your app to gain access to their account. Since this is a valid scenarion, it should be possible to identify this in your own code (I can't figure out if it's possible to hook into the authenticate callback code).

**Comment by ThomasArdal** [comment]
Looks to be better support for this scenario in the Twitter provider:

Failed to accept the Twitter App Authorization. Therefore, authentication didn't proceed.

But it still throws an exception inside code that I cannot wrap in a try-catch.

**Comment by PureKrome** [comment]
So maybe return a null `UserInformation` instead?

**Comment by ThomasArdal** [comment]
I think that would be a better solution. And maybe an enum or similar
explaining what went "wrong"?
